const tobaccoImages=["tobacco_1.png", "tobacco_2.png", "tobacco_3.png", "tobacco_4.png", "tobacco_5.png", "tobacco_6.png", "tobacco_7.png", "tobacco_8.png"];
const screens=[...document.querySelectorAll(".screen")];document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>show(b.dataset.screen));function show(id){screens.forEach(s=>s.classList.toggle("active",s.id===id));if(id==="farm")render()}
const toast=document.getElementById("toast");function say(t){toast.textContent=t;toast.classList.add("show");clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove("show"),1600)}
const pop=document.getElementById("seedPopup");openSeeds.onclick=()=>pop.classList.remove("hidden");closeSeeds.onclick=()=>pop.classList.add("hidden");pop.querySelector(".dim").onclick=()=>pop.classList.add("hidden");
const names=["ラーク・マイルド","ラーク・スマートプラス","ラーク・クラフト","メビウス・オプション","メビウス・プレミアム","メビウス・ワン","セブンスター","ウィンストン","ケント"];let selected=null;
for(let i=0;i<9;i++){const b=document.createElement("button");b.onclick=()=>{selected=i;selectionText.textContent=names[i]+"を選択中です";pop.classList.add("hidden");say("畑をなぞって植えてください")};seedHotspots.appendChild(b)}
const coords=[[17,20],[38,20],[60,20],[82,20],[12,36],[32,36],[52,36],[72,36],[89,36],[18,52],[40,52],[62,52],[83,52],[13,68],[34,68],[54,68],[74,68],[89,68],[20,84],[43,84],[66,84],[84,84]];
let plants=JSON.parse(localStorage.getItem("okanonExactPlants")||"[]");coords.forEach((p,i)=>{const d=document.createElement("div");d.className="slot";d.dataset.i=i;d.style.left=p[0]+"%";d.style.top=p[1]+"%";field.appendChild(d)});
function save(){localStorage.setItem("okanonExactPlants",JSON.stringify(plants))}function near(x,y){const r=field.getBoundingClientRect();let best=null,dist=45;coords.forEach((p,i)=>{let d=Math.hypot(x-r.left-r.width*p[0]/100,y-r.top-r.height*p[1]/100);if(d<dist){best=i;dist=d}});return best}
function plant(e){if(selected===null)return;let i=near(e.clientX,e.clientY);if(i===null||plants.some(p=>p.i===i&&!p.harvested))return;plants.push({i,seed:selected,time:Date.now(),harvested:false});save();render()}let drag=false;field.onpointerdown=e=>{drag=true;plant(e)};field.onpointermove=e=>{if(drag)plant(e)};window.onpointerup=()=>drag=false;
function render(){field.querySelectorAll(".slot").forEach(s=>s.innerHTML="");let now=Date.now();plants.forEach(p=>{if(p.harvested)return;let s=field.querySelector(`[data-i="${p.i}"]`);let soil=document.createElement("div");soil.className="soil";s.appendChild(soil);let age=(now-p.time)/1000;if(age<10){let im=document.createElement("img");im.className="packet";im.src="assets/"+tobaccoImages[p.seed%tobaccoImages.length];s.appendChild(im)}else if(age<30){let d=document.createElement("div");d.className="sprout";d.textContent="🌱";s.appendChild(d)}else{let im=document.createElement("img");im.className="okano";im.src="assets/okano_character.png";s.appendChild(im)}})}setInterval(render,1000);
harvest.onclick=()=>{let ready=plants.filter(p=>!p.harvested&&Date.now()-p.time>=30000);if(!ready.length)return say("収穫できる岡野さんはいません");ready.forEach(p=>p.harvested=true);save();render();say(ready.length+"体収穫しました")};ship.onclick=()=>say("出荷機能は後から実装します");
for(let i=1;i<=10;i++){let b=document.createElement("button");b.textContent="音声"+i;b.onclick=()=>say("音声ファイル未設定");voiceButtons.appendChild(b)}
const payment=document.getElementById("paymentPopup");confirmTip.onclick=()=>{let n=Number(amountInput.value);if(!n)return say("金額を入力してください");paymentAmount.textContent="￥"+n.toLocaleString();payment.classList.remove("hidden")};cancelPayment.onclick=()=>payment.classList.add("hidden");payment.querySelector(".dim").onclick=()=>payment.classList.add("hidden");completePayment.onclick=()=>{payment.classList.add("hidden");say("支払い演出が完了しました")};render();